print("Escribe la cantidad de payasos que se han vendido.")
numPayasos = int(input())
print("Escribe la cantidad de muñecas que se han vendido.")
numMunhecas = int(input())
print("El peso del paquete será de", ((numPayasos * 112) + (numMunhecas * 75)), "gramos")
